version: 2.1


workflows:
  tests:
    jobs:
      - plone61py312

jobs:

  plone61py312:
    resource_class: medium
    docker:
      - image: webcloud7/plone-test:6.1.1-py312
      - image: webcloud7/keycloak-test:24.0.2
        environment:
        - KEYCLOAK_ADMIN: 'admin'
        - KEYCLOAK_ADMIN_PASSWORD: 'admin'
        - KC_HEALTH_ENABLED: 'true'
        - KC_METRICS_ENABLED: 'true'

    environment:
      PIP_FIND_LINKS: /wheelhouse/
      zope_i18n_compile_mo_files: "true"
      WSGI_SERVER_PORT: 65035

    steps:
      - checkout
      - run: pip install uv
      - run: make install
      - run: make lint
      - run: make test
